export const testOptions = [
    {
        label: "Selection",
        prop: "selection",
        type: "selection",
        width: "60",
    },
    {
        label: "No",
        prop: "no",
        type: "index",
        width: 60,
    },
    {
        label: "Test_Identifier",
        prop: "test_identifier",
        sortable: true,
        fixed: true,
        width: 140,
    },
    {
        label: "Test_Pair_ID",
        prop: "test_pair_id",
        sortable: true,
        width: 100,
    },
    {
        label: "Test_Count_No",
        prop: "test_count_no",
        sortable: true,
        width: 100,
    },
    {
        label: "Test_Queue",
        prop: "test_queue",
        sortable: true,
        width: 100,
    },
    {
        label: "Test_Queue_State",
        prop: "test_queue_state",
        sortable: true,
        width: 200,
    },
    {
        label: "Bidirection",
        prop: "bidirection",
        sortable: true,
        width: 100,
    },
    {
        label: "test_qp_num",
        prop: "test_qp_num",
        sortable: true,
        width: 100,
    },
    {
        label: "test_port_num",
        prop: "test_port_num",
        sortable: true,
        width: 100,
    },
    {
        label: "Server_Host_Name",
        prop: "server_host_name",
        width: 100,
    },
    {
        label: "Server_Card_Name",
        prop: "server_card_name",
        sortable: true,
        width: 100,
    },
    {
        label: "Server_Card_IPV4_Addr",
        prop: "server_card_ipv4_addr",
        sortable: true,
        width: 110,
    },
    {
        label: "Server_Card_Mac_Addr",
        prop: "server_card_mac_addr",
        sortable: true,
        width: 150,
    },
    {
        label: "Server_RDMA_Name",
        prop: "server_ifname",
        sortable: true,
        width: 90,
    },
    {
        label: "Server_Node_GID",
        prop: "server_gid",
        sortable: true,
        width: 90,
    },
    {
        label: "Client_Host_Name",
        prop: "client_host_name",
        sortable: true,
        width: 100,
    },
    {
        label: "Client_Card_Name",
        prop: "client_card_name",
        sortable: true,
        width: 100,
    },
    {
        label: "Client_Card_IPV4_Addr",
        prop: "client_card_ipv4_addr",
        sortable: true,
        width: 110,
    },
    {
        label: "Client_Card_Mac_Addr",
        prop: "client_card_mac_addr",
        sortable: true,
        width: 150,
    },
    {
        label: "Client_RDMA_Name",
        prop: "client_ifname",
        sortable: true,
        width: 90,
    },
    {
        label: "Client_Node_GID",
        prop: "client_gid",
        sortable: true,
        width: 90,
    },
    {
        label: "rdma_sendbw_flag",
        prop: "rdma_sendbw_flag",
        sortable: true,
        width: 90,
    },
    {
        label: "rdma_sendbw_costtime",
        prop: "rdma_sendbw_costtime",
        sortable: true,
        width: 90,
    },
    {
        label: "rdma_readbw_flag",
        prop: "rdma_readbw_flag",
        sortable: true,
        width: 90,
    },
    {
        label: "rdma_readbw_costtime",
        prop: "rdma_readbw_costtime",
        sortable: true,
        width: 90,
    },
    {
        label: "rdma_writebw_flag",
        prop: "rdma_writebw_flag",
        sortable: true,
        width: 90,
    },
    {
        label: "rdma_writebw_costtime",
        prop: "rdma_writebw_costtime",
        sortable: true,
        width: 90,
    },
    {
        label: "rdma_atomicbw_flag",
        prop: "rdma_atomicbw_flag",
        sortable: true,
        width: 100,
    },
    {
        label: "rdma_atomicbw_costtime",
        prop: "rdma_atomicbw_costtime",
        sortable: true,
        width: 100,
    },
    {
        label: "rdma_ethernetbw_flag",
        prop: "rdma_ethernetbw_flag",
        sortable: true,
        width: 110,
    },
    {
        label: "rdma_ethernetbw_costtime",
        prop: "rdma_ethernetbw_costtime",
        sortable: true,
        width: 110,
    },
    {
        label: "rdma_sendlat_flag",
        prop: "rdma_sendlat_flag",
        sortable: true,
        width: 90,
    },
    {
        label: "rdma_sendlat_costtime",
        prop: "rdma_sendlat_costtime",
        sortable: true,
        width: 90,
    },
    {
        label: "rdma_readlat_flag",
        prop: "rdma_readlat_flag",
        sortable: true,
        width: 90,
    },
    {
        label: "rdma_readlat_costtime",
        prop: "rdma_readlat_costtime",
        sortable: true,
        width: 90,
    },
    {
        label: "rdma_writelat_flag",
        prop: "rdma_writelat_flag",
        sortable: true,
        width: 90,
    },
    {
        label: "rdma_writelat_costtime",
        prop: "rdma_writelat_costtime",
        sortable: true,
        width: 90,
    },
    {
        label: "rdma_atomiclat_flag",
        prop: "rdma_atomiclat_flag",
        sortable: true,
        width: 100,
    },
    {
        label: "rdma_atomiclat_costtime",
        prop: "rdma_atomiclat_costtime",
        sortable: true,
        width: 100,
    },
    {
        label: "rdma_ethernetlat_flag",
        prop: "rdma_ethernetlat_flag",
        sortable: true,
        width: 110,
    },
    {
        label: "rdma_ethernetlat_costtime",
        prop: "rdma_ethernetlat_costtime",
        sortable: true,
        width: 110,
    },
    {
        label: "Update_time",
        prop: "update_time",
        sortable: true,
        width: 200,
    },
];
